### ISSUE TITLE
Usage Details 

### ISSUE THREAD

**Issue by kuldeeps1208** [utpalbora/IITHThesis#2]
Hi, 

Can you share the way to change Logo as per our requirement. The one used in the checked in code has been discontinued.

**Comment by utpalbora** [comment]
Hi, Please provide more details on what has changed? You can look into comon/iiththesis.cls to see how the logo is created in LaTeX. I have one more version with Telugu text in it. You can refer to my thesis [here](https://utpalbora.com/documents/Utpal_thesis_CSE_final_singed.pdf).

**Comment by kuldeeps1208** [comment]
Yeah you pointed out the exact thing. I want to change the logo to the one that has Telugu text as well. Can you the share the latex copy of your thesis for reference. 
I'm unable to understand the way to refer Figures and Tables in the Github Format. This will save my time. Thanks for understanding.

**Comment by kuldeeps1208** [comment]
I have added the telugu language line in \node section in .cls file. Thanks for the help.
